import json
import os
from dotenv import load_dotenv

from flask import jsonify, request, Blueprint
import pymongo
from bson import json_util
from bson.objectid import ObjectId

client = pymongo.MongoClient(os.environ.get("MONGO_URI"))
db = client['shop_manager']
accounts = db['accounts']

authentication_bp = Blueprint('authentication', __name__)


@authentication_bp.route('/register', methods=['GET'])
def hello_register():
    return 'Hello Kana!'


@authentication_bp.route('/register', methods=['POST'])
def register():
    """
    Add a new user to the database in the following format
    {
        '_id': ObjectId('<KEY>') - Generated by DB
        'username': str,
        'password': str'
    }
    :return:
    """
    data = request.json
    query = {'username': data['username']}
    if accounts.find_one(query):
        return json.loads(json_util.dumps({
            'message': 'This username is already taken'
        }))
    result = accounts.insert_one(data)
    # print(result.inserted_id)
    return json.loads(json_util.dumps({
        'message': 'ok',
        'userId': result.inserted_id
    }))


@authentication_bp.route('/login', methods=['GET'])
def hello_login():
    return 'Hello Kana!'


@authentication_bp.route('/login', methods=['POST'])
def login():
    """
       Login
       {
           'username': str,
           'password': str'
       }
       :return:
       """
    data = request.json
    query = {
        'username': data['username'],
        'password': data['password']
    }
    if accounts.find_one(query):
        return json.loads(json_util.dumps({
            'message': 'ok'
        }))
    return json.loads(json_util.dumps({
                'message': 'Invalid username or password'
            }))
